apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-upload
  template:
    metadata:
      labels:
        app: video-upload
    spec:
      volumes:
        - name: gcloud-storage-api
          secret:
            secretName: gcloud-storage-api
      containers:
        - image: webflix/video-upload:2021-01-06-05-12-59
          name: video-upload
          volumeMounts:
            - name: gcloud-storage-api
              mountPath: /var/secrets/gcloud-storage
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/gcloud-storage/key.json
            - name: APPCONFIG_GCLOUDSTORAGE_PROJECTID
              valueFrom:
                secretKeyRef:
                  name: gcloud-storage-api
                  key: project_id
            - name: APPCONFIG_GCLOUDSTORAGE_BUCKETNAME
              valueFrom:
                secretKeyRef:
                  name: gcloud-storage-api
                  key: bucket_name
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              valueFrom:
                secretKeyRef:
                  name: kubernetes-postgres-connect
                  key: database_url
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubernetes-postgres-connect
                  key: user
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubernetes-postgres-connect
                  key: password
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: video-upload
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: video-upload
